github_owner              = "NikolaiGorovikov"
github_repo               = "timeandnotes"
github_branch             = "main"
domain_name               = "timeandnotes.com"
subdomain                 = "www"